### ISSUE TITLE
Non-responsiveness of Response Options

### ISSUE THREAD

**Issue by EliRuss** [MCEMS/dispatch#21] opened 2016-03-03 19:12 UTC
Conducted testing today with Campus Safety. After I selected "Resp" I showed up on the console, but when I selected "OnScen" this update did not appear.

**Comment by benburwell** [comment] 2016-03-03 23:20
@eliruss, did it show up in the app? Did you wait at least a minute? Also, do you remember what call this was for?

**Comment by EliRuss** [comment] 2016-03-03 23:22
Yes, it showed up in the app. Although, in one case, I did have to select the same option twice because it did not register the first time. We waited several minutes. This happened on all of the test calls conducted today.

**Comment by benburwell** [comment] 2016-03-08 01:32
Closing as a duplicate of #22 -- see comments there.

**Closed as completed by benburwell** 2016-03-08 01:32 UTC
